SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;


CREATE DATABASE  clinic;

USE clinic;


CREATE TABLE IF NOT EXISTS patients(
    pid INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pname VARCHAR(20) NOT NULL,
    exam_type VARCHAR(20),
    amount INT NOT NULL,
    submission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS doctors(

    id INT AUTO_INCREMENT PRIMARY KEY,
    dusername VARCHAR(100) NOT NULL UNIQUE,
    demail VARCHAR(20),
    dpsswrd VARCHAR(255) NOT NULL

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS receptionists(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    rusername VARCHAR(20) NOT NULL UNIQUE,
    remail VARCHAR(20),
    rpsswrd VARCHAR(255) NOT NULL

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;